spring.application.name=challenge
gemini.api.key=${GEMINI_API_KEY}
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent

spring.web.error.include-stacktrace=never
spring.web.error.include-message=always
spring.web.error.include-path=never